### PR TITLE
RSS custom format

### PR DESCRIPTION
**Pull request by examknow**
Per discussion on IRC. Allows channels to specify the RSS announcement format. By default, the behavior will be the same.

### CODE REVIEW

**Comment by benharri** [comment]
any way to use other fields? for example I'd like to show the guid or comments field instead of the link

**Comment by examknow** [comment]
Now, setting adding a string inside curly braces will make the bot report that key from inside the `entry` dict.

**Comment by benharri** [comment]
Looks like it's working - not sure why `<guid>` gets munged to `id` but that's fine :)

**Comment by examknow** [comment]
Very well then. I'll remove WIP and call this ready for review.

**Pull request merged**
