### PR TITLE
Add gogs support

### PR DESCRIPTION
**Pull request by eskimo**
It works ¯\\\_(ツ)_/¯

### CODE REVIEW

**Comment by eskimo** [comment]
Ok now it works.

**Comment by eskimo** [comment]
Also, hi Jess.

**Comment by jesopo** [comment]
what's the difference between Gogs and Gitea webhooks

**Comment by eskimo** [comment]
Well, the Gitea module didn't work because you specifically look for the X-Gitea-Event header, but actually now that I am looking at Gitea source, seems like it also adds the Gogs header https://github.com/go-gitea/gitea/blob/bf6014644401dd3fdf9031670b3a00ccd866f49f/modules/webhook/deliver.go#L98

Another reason for making it it's own module though would be that I have no clue if there's any differences since I don't know Gitea or Gogs enough, and Gogs may do some things slightly different and it might need to be split up anyway once bugs are discovered?

**Comment by jesopo** [comment]
is this a copy of `gitea.py` with the header changed? if so, i'd prefer to change `gitea.py` to something like `gitea-gogs.py` and have it support both

**Comment by eskimo** [comment]
Yeah, I wasn't aware that Gitea also sends the Gogs header. But still, haven't been using it long enough to know if there's any differences between Gogs and Gitea webhooks yet.

**Comment by eskimo** [comment]
Yeah, I wasn't aware that Gitea also sends the Gogs header. But still, haven't been using it long enough to know if there's any differences between Gogs and Gitea webhooks yet.

**Pull request closed without merging**
