### PR TITLE
Create bitbot.service

### PR DESCRIPTION
**Pull request by TehPeGaSuS**
Systemd script to use with Ubuntu 18.04 LTS (tested) or similar.

### CODE REVIEW

**Comment by jesopo** [comment]
Thanks! I'm not very sure about `.service` best-practice but should `ExecStart` instead use `/usr/bin/env python3`? like hashbangs do?

**Comment by jesopo** [comment]
Also can you move this in to a subdirectory? e.g. `./docs/bitbot.service`? Don't want to clutter up the root directory too much

**Comment by jesopo** [comment]
Also SIGHUP currently does nothing on BitBot? Should `ExecReload` see the whole bot restarted or should it see things like config and modules being reloaded?

**Comment by TehPeGaSuS** [comment]
> Also SIGHUP currently does nothing on BitBot? Should `ExecReload` see the whole bot restarted or should it see things like config and modules being reloaded?

If possible it should make the bot save the current state and reload config and plugins via SIGHUP

**Comment by jesopo** [comment]
Leave it as SIGHUP and I'll implement reloading config and modules on SIGHUP soon (#49)

**Comment by jesopo** [comment]
thank you very much!

**Pull request merged**
