### PR TITLE
Use cyan rather than grey

### PR DESCRIPTION
**Pull request by japanoise**
Grey is poorly supported and may come out black on some schemes

### CODE REVIEW

**Comment by jesopo** [comment]
these colours were chosen in cooperation with a few other projects - some of them are quite large. each colour has their own downside and I specifically remember we used to use cyan for something but had to change it - can't remember what though.

I've not come across a lot of people with this issue (3 out of many hundreds) and, really, if a terminal is showing "grey" as black, seems to me to be an issue with the terminal. tweak your palette maybe?

**Comment by japanoise** [comment]
It's not really a question of "my" palette. I'm using a default unriced snazzy: https://github.com/sindresorhus/hyper-snazzy which is a popular mainstream colorscheme. The same issue occurs with the widely popular base16 colorschemes, as well as the solarized schemes, and just about every scheme I've tried on terminal.sexy.

The question becomes "should I really be tweaking my terminal to work around poorly-behaved software?". Especially since a lot of other poorly-behaved software assumes that that color is black and uses it as a black background.

**Comment by jesopo** [comment]
My software does not assume that.

If this issue was more widespread, i would know about it.

I'd rather not make a tweak this tiny that will be a change for everyone that uses bitbot's git webhooks just for this.

You could just `/ignore bitbot` if it bothers you! Or fix your broken terminal emulator.

**Comment by japanoise** [comment]
this isn't going anywhere

**Pull request closed without merging**
